### ISSUE TITLE
Staff Question #1:  Updates Edit

### ISSUE THREAD

**Issue by bradbergeron90** [mpiaria/adjustments#1]
Have you ever or do you use UpdatesEdit?

**Comment by mpiaria** [comment]
The updated_subform calls [dbo].[adjustments_update2] to get its data.  This stored procedure selects records from adjustments_updates1, which is empty.  They don't use this form at all.  You can get rid of it, or you can implement it towards the end if you have time.  For now, there's no need to worry about it at all.
