### ISSUE TITLE
Add Ryan Smith-Burns to the Staff combo box.

### ISSUE THREAD

**Issue by mpiaria** [mpiaria/adjustments#3]
It looks like Ryan Smith-Burns isn’t able to add an adjustment to the database since she isn’t listed under the Staff drop down. Can she be added?

![image001](https://cloud.githubusercontent.com/assets/8315738/7372621/7360a264-ed8d-11e4-97f2-7f1fe00055b6.png)

**Comment by bradbergeron90** [comment]
I added his name to a version of the current database that I have, Problem is I don't know how to save the database as a "Read only" and than put it in the "Common/Adjustment Database" floder for the employees to use. Please advise

**Comment by mpiaria** [comment]
Okay.  I'll be in tomorrow.  We can run through it then.  Jake also knows how to do it if you see him around first.  Thanks for taking care of it so quickly.
